### ISSUE TITLE
ReferenceError: Image is not defined

### ISSUE THREAD

**Issue by ZaxmkE** [fast-average-color/fast-average-color#49]
Using Node.js and trying to get the average color of a image url, but when it gets to it. I get this error.

C:\Users\assas\node_modules\fast-average-color\dist\index.common.js:163
        return this._bindImageEvents(new Image(resource), options);
                                         ^

ReferenceError: Image is not defined
    at FastAverageColor.getColorAsync (C:\Users\assas\node_modules\fast-average-color\dist\index.common.js:163:42)
    at Request._callback (C:\Users\assas\Desktop\Metrix\main.js:192:13)
    at Request.self.callback (C:\Users\assas\node_modules\request\request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (C:\Users\assas\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (C:\Users\assas\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)

**Comment by hcodes** [comment]
This package is only for the browser, not for Node.js.

**Comment by hcodes** [comment]
Example for Node.js:
https://github.com/fast-average-color/examples/blob/master/nodejs/index.js
